version: "{build}"

image: Visual Studio 2022

environment:
  nodejs_version: "18"

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - choco install googlechrome --no-progress --yes
  - choco install firefox --no-progress --yes
  - node --version
  - npm --version
  - npm ci

test_script:
  - npm test

build: off